#!/bin/bash
#SBATCH --job-name=ggchem_build
#SBATCH --time=0:30:00
#SBATCH --partition=astro2_short
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=10G
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=ALL

module load astro gdb
cd GGchem/src16
make
