#!/bin/bash
# SLURM resource specifications
# (use an extra ‘#’ in front of SBATCH to comment-out any unused options)
#SBATCH --job-name=marcs # shows up in the output of ‘squeue’
#SBATCH --time=2:00:00       # specify the requested wall-time
#SBATCH --partition=astro2_devel   # specify the partition to run on
#SBATCH --nodes=1              # number of nodes allocated for this job
#SBATCH --mem-per-cpu=30G
#SBATCH --ntasks-per-node=1    # number of MPI ranks per node
#SBATCH --cpus-per-task=1       # number of OpenMP threads per MPI rank
#SBATCH --mail-type=ALL

module load astro gdb
### INPUT AND TEMP FOLDERS ###
CWD=$(pwd)
TMPDIR=$(mktemp -p /dev/shm/ -u)

in_dir='./models/basic_test/t700g29/'
out_dir='./models/basic_test/t700g29/'
in_filename=${in_dir}t070g29exo50Earth_krome_on_irrad_on
out_filename=${out_dir}t070g29exo50Earth_krome_on_irrad_on_new

#mkdir ${out_dir}
mkdir $TMPDIR

### INPUT FILES ###
cp marcs.input mxms7.input
cp ${in_filename}.arciv arcivaaa.dat

### COPY FILES TO TEMP DIRECTORY ###
cp arcivaaa.dat $TMPDIR/
rm arcivaaa.dat
#cp *.txt $TMPDIR/
cp -r data $TMPDIR/
cp *.inc $TMPDIR/
cp *.dat $TMPDIR/
cp mxms7.input $TMPDIR/
cp marcs $TMPDIR/
cp -r GGchem $TMPDIR/
### FOR NONEQ RUNS
cp $CWD/krome/MARCS_build/*.dat $TMPDIR/
cp -r $CWD/krome $TMPDIR



cd $TMPDIR 



./marcs

### COPY FILES AFTER RUN ###
cp arcivaab.dat    	$CWD/${out_filename}.arciv
cp mxmodel.dat     	$CWD/${out_filename}.dat
cp data/elabund.dat $CWD/${out_dir}
cp data/jonabs.dat $CWD/${out_dir}
cp data/mol_names.dat $CWD/${out_dir}
cp mxms7.input $CWD/${out_dir}
cp $CWD/runmarcs    $CWD/${out_dir}

### THESE ARE OPTIONAL OUTPUTS FOR GGCHEM AND DEBUGGING
#cp $TMPDIR/pp.dat $CWD/${out_dir}
#cp $TMPDIR/GGchem_ppel $CWD/${out_dir}
#cp $TMPDIR/nasa2ggchem.dat $CWD/${out_dir}

### THESE AREA OPTIONAL OUTPUTS FOR KROME
#cp $TMPDIR/krome_full_output.dat $CWD/${out_dir}/krome_full_output.dat
cp $TMPDIR/krome_final_output.dat $CWD/${out_dir}/krome_final_output.dat
#if [ -f "KROME_ERROR_REPORT" ] ; then
#cp KROME_ERROR_REPORT $CWD
#fi



rm -rf $TMPDIR
