
!###################################################
! WARNING:This is a test auto-generated by KROME, in order to
! show a bare-minimal code to call the KROME's subroutine.
! Most of the values could not be appropriate for your
! problem, since this test is only intended as a general
! purpose example.

program test
  use krome_main !use krome (mandatory)
  use krome_user !use utility (for krome_idx_* constants and others)
  implicit none
  integer,parameter::nsp=krome_nmols !number of species (common)
  real*8::Tgas,dt,x(nsp),spy,tmax,tt
  integer istep

  spy = 3.65d2 * 2.4d1 * 3.6d3 !seconds per year

  call krome_init() !init krome (mandatory)

  x(krome_idx_M) = 1.53670791759876E+022 
  x(krome_idx_O) = 347740113314.222 
  x(krome_idx_O2) = 1.071069838492632E+022 
  x(krome_idx_O3) = 205800221.913038
!  x(krome_idx_M) = 1.53670791759876E+022
  tt = 0
  Tgas = 1000 !gas temperature (K)
  dt = 1d-20 * spy !time-step (s)
  tmax = 1d20*spy
  !call the solver
  

  do
  call krome(x(:), Tgas, dt) !call KROME

     !dump every 10 steps
     if(mod(istep,10)==0) then
        print '(F11.2,a2)',tt/tmax*1d2," %"
        write(55,'(999E17.8e3)') tt/spy,x(:)
     end if
     dt=dt*1.05
     tt = tt + dt !increase timei
     if(tt>tmax) exit !exit condition
     istep = istep + 1
  end do
  
  print *,"Test OK!"
  print *,x(:)
end program test

